### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by jxh4945777** [Dongcf/BiLSTM-Attention_CN_Text_Clf_Pytorch#1]
你好，在使用源码过程中出现如下报错，请问该如何修正呢，感谢~
或者是否有完整的Readme.md
![image](https://user-images.githubusercontent.com/43498963/64542859-df638400-d356-11e9-8dfd-9aa069f0dff8.png)

**Comment by jxh4945777** [comment]
![image](https://user-images.githubusercontent.com/43498963/64551930-c4017480-d368-11e9-8ac3-ffea21e4c683.png)
已解决

**Comment by Dongcf** [comment]
这是python csv读取文件偶尔会出现的错误 还有一种方法是  设置系统的 sys.maxsize
